---
# debug: true
# silent: false
# dir: .
# report_type: JSON
# report_location: .
# include_dev: false
# color_output: false
# policies:
#  - policy_type: license_type
#    deny_list: APSL,GPL-PA,JSON
#  - policy_type: package_name
#    deny_list: jsont