language: python
python:
  - 3.6
  - 3.7
install:
  - python --version
  - pip install -U pip
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
  - "export OCHRONA_API_URL=http://localhost:5000/python/analyze"
  - pip install pipenv
  - pipenv install --dev
script:
  - pytest --cov=./
  - bandit ./ochrona -r -n 3 -lll
  - black --check ./ochrona
after_success:
  - codecov
