language: python
python:
  - 3.6
  - 3.7
install:
  - python --version
  - pip install -U pip
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
  - "export OCHRONA_API_URL=http://localhost:5000/python/analyze"
  - "export TMP_OCHRONA_API_KEY=$OCHRONA_API_KEY"
  - "unset OCHRONA_API_KEY"
  - pip install pipenv
  - pipenv install --dev
script:
  - pytest --cov=./
  - bandit ./ochrona -r -n 3 -lll
  - black --check ./ochrona
  - unset OCHRONA_API_URL
  - export OCHRONA_API_KEY=$TMP_OCHRONA_API_KEY
  - cat ./Pipfile.lock 
  - ochrona --file ./Pipfile.lock
after_success:
  - codecov
