
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  package:
    name: PyPI Upload
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade --upgrade-strategy=eager pip setuptools wheel twine
        python -m pip install -r requirements.txt

    - name: Build wheels
      run: |
        python setup.py sdist bdist_wheel

    - name: version
      run: echo "::set-output name=version::$(cat ./ochrona/__init__.py | grep -Eio '(\d{1,}\.\d{1,}\.\d{1,}[a0-9]*)')"
      id: version

    - name: variable
      run: |
        echo ${{ steps.version.outputs.version }}
        echo "===="
        cat ./ochrona/__init__.py | grep -Eio '(\d{1,}\.\d{1,}\.\d{1,}[a0-9]*)' 

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.version }}
        release_name:  v${{ steps.version.outputs.version }}
        draft: false
        prerelease: false

    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
        # repository_url: https://test.pypi.org/legacy/
        packages_dir: dist/
